call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-forms-client -Dfile=adobe-forms-client.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-livecycle-client -Dfile=adobe-livecycle-client.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-taskmanager-client -Dfile=adobe-taskmanager-client.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-usermanager-client -Dfile=adobe-usermanager-client.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=jbossall-client -Dfile=jbossall-client-4.2.0.GA.jar -Dpackaging=jar -Dversion=4.2.0.GA
call mvn install:install-file -DgroupId=com.adobe -DartifactId=serializer -Dfile=serializer.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=axis -Dfile=axis.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=activation -Dfile=activation.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=jaxrpc -Dfile=jaxrpc.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-utilities -Dfile=adobe-utilities.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=commons-codec -Dfile=commons-codec-1.3.jar -Dpackaging=jar -Dversion=1.3
call mvn install:install-file -DgroupId=com.adobe -DartifactId=jaxen -Dfile=jaxen-1.1.1.jar -Dpackaging=jar -Dversion=1.1.1
call mvn install:install-file -DgroupId=com.adobe -DartifactId=commons-logging -Dfile=commons-logging.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=dom3-xml-apis -Dfile=dom3-xml-apis-2.5.0.jar -Dpackaging=jar -Dversion=2.5.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=mail -Dfile=mail.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=xercesImpl -Dfile=xercesImpl.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=saaj -Dfile=saaj.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=xbean -Dfile=xbean.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=wsdl4j -Dfile=wsdl4j.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=xalan -Dfile=xalan.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=log4j -Dfile=log4j.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=commons-discovery -Dfile=commons-discovery.jar -Dpackaging=jar -Dversion=1.0
call mvn install:install-file -DgroupId=com.adobe -DartifactId=adobe-contentservices-client -Dfile=adobe-contentservices-client.jar -Dpackaging=jar -Dversion=1.0